name: mini-soccer # change this to your app name
services:
  user-service: # change this to your service name
    container_name: user-service # change this to your service name
    # image: arvelbudion01/user-service:1 # change this to your image name (only for production)
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001" # change this to your port
    env_file:
      - .env